### ISSUE TITLE
empty string on update queries

### ISSUE THREAD

**Issue by lequarti** [R0FM/YSPDO#1]
Hi, 

Since you check :
`if(!empty($val))` (line 394)

When you have an update instruction and the string is empty, it throws an exception, (mismatch parameter number).

`
$DB->update('blazer', [
	    'Country' =>  intval($_POST ['county']),
            'CountryOther' => strval($_POST ['countother'])
], [
            'ID_user' => intval($sess['id'])
]);`

When strval($_POST ['countother']) is not empty, it's fine, but once you have an empty string, it sucks.

**Comment by lequarti** [comment]
The same applies also to 0 (int)

**Comment by R0FM** [comment]
Hi, I have already fixed this class error on localhost, which consists of just removing this condition.

Thank you for notifying
